# Site settings
title: Team Torch
email: teamtorch5942@gmail.com
url: https://teamtorch5942.github.io
description: "FTC Team Torch 5942"
skills: "FTC Team from North Hills, CA"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00e676 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 242424 #FD6E8A
  secondary-dark: 151515 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/teamtorch5942
  - title: github
    url: http://github.com/teamtorch5942

# Postal address (add as many lines as necessary)
address:
  - line: 8854 Haskell Ave
  - line: North Hills, CA 91343

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
